// <auto-generated />
using System;
using CESP.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CESP.Database.Migrations
{
    [DbContext(typeof(CespContext))]
    [Migration("20190308143916_Seed-Feedbacks")]
    partial class SeedFeedbacks
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("CESP.Database.Context.Activities.Models.ActivityDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime>("End")
                        .HasColumnName("end");

                    b.Property<string>("Info")
                        .HasColumnName("info");

                    b.Property<string>("Name")
                        .HasColumnName("name");

                    b.Property<string>("ShortInfo")
                        .HasColumnName("short_info");

                    b.Property<DateTime>("Start")
                        .HasColumnName("start");

                    b.HasKey("Id");

                    b.ToTable("activities");
                });

            modelBuilder.Entity("CESP.Database.Context.Education.Models.CourseDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("DurationInfo")
                        .HasColumnName("duration_info");

                    b.Property<string>("Info")
                        .HasColumnName("info");

                    b.Property<string>("InstructionPdf")
                        .HasColumnName("instruction_pdf");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasMaxLength(256);

                    b.Property<string>("NativeInfo")
                        .HasColumnName("native_info");

                    b.Property<string>("NativeName")
                        .HasColumnName("native_name")
                        .HasMaxLength(256);

                    b.Property<string>("ShortInfo")
                        .HasColumnName("short_info");

                    b.HasKey("Id");

                    b.ToTable("cources");
                });

            modelBuilder.Entity("CESP.Database.Context.Education.Models.LanguageLevelDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Info")
                        .HasColumnName("info");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasMaxLength(256);

                    b.Property<string>("NativeName")
                        .HasColumnName("native_name")
                        .HasMaxLength(256);

                    b.Property<int?>("Rang")
                        .HasColumnName("rang");

                    b.HasKey("Id");

                    b.ToTable("language_levels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "A1.1",
                            Rang = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "A1.2",
                            Rang = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "A2.1",
                            Rang = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "A2.2",
                            Rang = 4
                        },
                        new
                        {
                            Id = 5,
                            Name = "B1.1",
                            Rang = 5
                        },
                        new
                        {
                            Id = 6,
                            Name = "B1.2",
                            Rang = 6
                        },
                        new
                        {
                            Id = 7,
                            Name = "B2.1",
                            Rang = 7
                        },
                        new
                        {
                            Id = 8,
                            Name = "B2.2",
                            Rang = 8
                        },
                        new
                        {
                            Id = 9,
                            Name = "C1.1",
                            Rang = 9
                        },
                        new
                        {
                            Id = 10,
                            Name = "C1.2",
                            Rang = 10
                        },
                        new
                        {
                            Id = 11,
                            Name = "C2.1",
                            Rang = 11
                        },
                        new
                        {
                            Id = 12,
                            Name = "C2.2",
                            Rang = 12
                        });
                });

            modelBuilder.Entity("CESP.Database.Context.Education.Models.SpeakingClubMeetingDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime>("Date")
                        .HasColumnName("date");

                    b.Property<string>("Info")
                        .HasColumnName("info");

                    b.Property<int?>("MaxLanguageLevelId")
                        .HasColumnName("max_language_level_id");

                    b.Property<int?>("MinLanguageLevelId")
                        .HasColumnName("min_language_level_id");

                    b.Property<string>("Name")
                        .HasColumnName("name");

                    b.Property<int?>("TeacherId")
                        .HasColumnName("teacher_id");

                    b.Property<int?>("max_language_meeting_fk");

                    b.Property<int?>("min_language_meeting_fk");

                    b.Property<int?>("teacher_meeting_fk");

                    b.HasKey("Id");

                    b.HasIndex("max_language_meeting_fk");

                    b.HasIndex("min_language_meeting_fk");

                    b.HasIndex("teacher_meeting_fk");

                    b.ToTable("speaking_club_meetings");
                });

            modelBuilder.Entity("CESP.Database.Context.Education.Models.StudentGroupDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int?>("CountStudentsMax")
                        .HasColumnName("count_students_max");

                    b.Property<int?>("CountStudentsMin")
                        .HasColumnName("count_students_min");

                    b.Property<int>("CourseId")
                        .HasColumnName("course_id");

                    b.Property<string>("Description")
                        .HasColumnName("description");

                    b.Property<bool>("IsAvailable")
                        .HasColumnName("available");

                    b.Property<DateTime>("Start")
                        .HasColumnName("date_start");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("student_groups");
                });

            modelBuilder.Entity("CESP.Database.Context.Education.Models.StudentGroupPriceDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<int>("PriceId");

                    b.Property<int>("StudentGroupId")
                        .HasColumnName("student_group_id");

                    b.HasKey("Id");

                    b.HasIndex("PriceId");

                    b.HasIndex("StudentGroupId");

                    b.ToTable("student_group_prices");
                });

            modelBuilder.Entity("CESP.Database.Context.Education.Models.TeacherDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Info")
                        .HasColumnName("info");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(256);

                    b.Property<string>("Post")
                        .HasColumnName("post")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.ToTable("teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Info = "Йосу — преподаватель-носитель испанского языка из Барселоны с большим опытом работы. Имеет международный сертификат ELE для преподавания испанского как иностранного (от International House Barcelona, утвержденным Университетом Барселоны). Кроме того Йосу является дипломированным экзаменатором экзамена DELE, это значит что он может как принимать экзамен, так и подготавливать студентов для сдачи DELE. И конечно, имеет сертификат, подтверждающий квалификацию преподавателя от Института Сервантеса г. Москвы. Работает как со взрослыми, так и с детьми у которых всегда имеет особенный успех. Уроки проходят в дружественной, неформальной обстановке, что способствует эффективному и быстрому усвоению материала. Владеет русским языком.",
                            Name = "Йосу",
                            Post = "преподаватель"
                        },
                        new
                        {
                            Id = 2,
                            Info = "Анхель – опытный преподаватель испанского языка из Малаги. Позитивный, открытый и добрый. На уроках любит разложить все объяснения по полочкам, что облегчает процесс усвоения материала. В Москве преподаёт испанский с 2012 прекрасно ладит как со взрослыми, так и с детьми, готовит свои уроки индивидуально, с учетом потребностей, интересов и особенностей каждой группы, но конечно в рамках Международного стандарта преподавания испанского языка иностранцам. Увлекается классической музыкой. Прекрасно владеет русским языком.",
                            Name = "Анхель",
                            Post = "преподаватель"
                        },
                        new
                        {
                            Id = 3,
                            Info = "Рафаэль - преподаватель-носитель испанского и каталанского языков из Барселоны. В Россию приехал в 2013 году, до этого жил и работал в Англии. Имеет сертификаты Института Сервантеса о специальной подготовке преподавателей которые дают право преподавать язык иностранным студентам. Открытый, жизнерадостный и общительный. Ему нравится путешествовать, познавать новые культуры и обмениваться своим опытом с другими людьми. Творчески подходит к подготовке своих уроков испанского и каталанского и поэтому его занятия всегда динамичные и интересные. На своих уроках он использует коммуникативную методику, соответствующую международным стандартам. На занятиях у Рафаэля при погружении в языковую среду студент с первых уроков начинает говорить на испанском языке. Прекрасно ладит как со взрослыми, так и с детьми и подростками. Владеет русским языком.",
                            Name = "Рафаэль",
                            Post = "преподаватель"
                        },
                        new
                        {
                            Id = 4,
                            Info = "Альберто преподаватель-носитель испанского языка, родился в Гранаде. Имеет обширный опыт преподавания испанского языка для иностранцев, как в Испании так и в России. На занятиях с Альберто всегда интересно и весело. Студенты активно вовлечены в учебный процесс. Альберто знает древние языки, такие как: латинский и греческий, что позволяет ему давать более глубокий материал по испанскому языку. Так же свободно владеет русским языком.",
                            Name = "Альберто",
                            Post = "преподаватель"
                        },
                        new
                        {
                            Id = 5,
                            Info = "Хулио - квалифицированный преподаватель испанского языка, преподает испанский в общей сложности около 9 лет. Аккредитован как преподаватель ELE (испанский язык, как иностранный) в International House Madrid, а также Институтом Сервантеса в Москве. Хулио является аккредитованным экзаменатором экзамена DELE для уровней от А1 до B2 и в совершенстве владеет коммуникативной методикой преподавания языка. Всегда уделяет внимание каждому студенту, занятия проходят в дружеской обстановке.",
                            Name = "Хулио",
                            Post = "преподаватель"
                        },
                        new
                        {
                            Id = 6,
                            Info = "Алехо - преподаватель испанского языка с более чем девятилетним опытом работы. Он отлично понимает потребности и трудности своих учеников, так как сам учился русскому, английскому, французскому и португальскому языкам, и знает все \"подводные камни\" при изучении иностранных языков и, несомненно, поможет их избежать своим судентам. Алехо очень позитивный, понимающий и терпеливый человек, что особенно важно в профессии преподавателя. Алехо имеет диплом бакалавра по экономике, также успешно прошел курсы по повышению квалиффикации в Институте Сервантеса. Кроме того, является официальным экзаменатором Dele для уровней A, B и C.",
                            Name = "Алехо",
                            Post = "преподаватель"
                        },
                        new
                        {
                            Id = 7,
                            Info = "Пабло - преподаватель испанского языка из Венесуэлы. Работает как со взрослыми, так и с детскими группами, у которых всегда имеет особенный успех. Веселый, молодой, харизматичный преподаватель. Всегда тщательно подбирает материалы для каждого занятия. Очень ответственно относится к своей работе, и результатам своих студентов.",
                            Name = "Пабло",
                            Post = "преподаватель"
                        },
                        new
                        {
                            Id = 8,
                            Info = @"Джонатан жизнелюбивый и опытный преподаватель из Испании (Барселона). Имеет педагогическое образование (воспитатель в детском саду), что дало ему возможность работать с детьми разных возрастов и преподавать им испанский язык как иностранный. 
                    Уже три года Джонатан обучает испанскому языку как детей, так и взрослых. Программу занятий для каждого ученика подбирает индивидуально и адаптирует методику под его особенности, уровень владения языком, возраст и потребности. Его занятия всегда увлекательны и динамичными, и при всем при этом, эффективные и полезные.Владеет русским языком.",
                            Name = "Джонатан",
                            Post = "преподаватель"
                        },
                        new
                        {
                            Id = 9,
                            Info = "Юлия разносторонний и творческий человек. Закончила с отличием филологический факультет МГУ им М.В. Ломоносова. Прошла стажировку в Университете Барселоны. Три года работает преподавателем испанского и каталанского языков. Владеет коммуникативной методикой преподавания для иностранцев. На своих уроках особое внимание уделяет грамматике и разговорной лексике, а также культуре и литературе стран изучаемого языка.",
                            Name = "Юлия",
                            Post = "преподаватель, лингвист"
                        });
                });

            modelBuilder.Entity("CESP.Database.Context.Payments.Models.CurrencyDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.ToTable("currencies");
                });

            modelBuilder.Entity("CESP.Database.Context.Payments.Models.PaymentPeriodDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasColumnName("info")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.ToTable("payment_periods");
                });

            modelBuilder.Entity("CESP.Database.Context.Payments.Models.PriceDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<decimal>("Cost")
                        .HasColumnName("cost");

                    b.Property<int>("CurrencyId")
                        .HasColumnName("currency_id");

                    b.Property<decimal?>("Discount")
                        .HasColumnName("discount");

                    b.Property<int?>("DiscountPer")
                        .HasColumnName("discounter");

                    b.Property<int>("PaymentPeriodId")
                        .HasColumnName("payment_period_id");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("PaymentPeriodId");

                    b.ToTable("prices");
                });

            modelBuilder.Entity("CESP.Database.Context.Press.Models.PressDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("BlogUrl")
                        .HasColumnName("blog_url");

                    b.Property<DateTime>("Date")
                        .HasColumnName("date");

                    b.Property<string>("Info")
                        .HasColumnName("info");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasMaxLength(256);

                    b.Property<string>("Source")
                        .HasColumnName("source")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.ToTable("presses");
                });

            modelBuilder.Entity("CESP.Database.Context.Schedules.Models.ScheduleDayDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.ToTable("schedule_days");
                });

            modelBuilder.Entity("CESP.Database.Context.Schedules.Models.ScheduleDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime>("EndLessonTime")
                        .HasColumnName("lesson_end");

                    b.Property<int>("ScheduleDayId")
                        .HasColumnName("schedule_day_id");

                    b.Property<DateTime>("StartLessonTime")
                        .HasColumnName("lesson_start");

                    b.Property<int>("StudentGroupId")
                        .HasColumnName("student_group_id");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleDayId");

                    b.HasIndex("StudentGroupId");

                    b.ToTable("schedules");
                });

            modelBuilder.Entity("CESP.Database.Context.Schools.Models.SchoolDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Info")
                        .HasColumnName("info");

                    b.Property<string>("Location")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasMaxLength(256);

                    b.Property<string>("ShortInfo")
                        .HasColumnName("short_info");

                    b.HasKey("Id");

                    b.ToTable("schools");
                });

            modelBuilder.Entity("CESP.Database.Context.Users.Models.FeedbackDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime>("Date")
                        .HasColumnName("date");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnName("message");

                    b.Property<string>("Signature")
                        .HasColumnName("signature");

                    b.Property<int?>("SourceId")
                        .HasColumnName("feedback_source_id");

                    b.Property<int?>("UserId")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("UserId");

                    b.ToTable("feedbacks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2016, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Занятиями очень довольна. Уроки проходят на одном дыхании; в доброжелательной обстановке. Преподаватель Йосу Санчес все понятно объясняет. Отработка тем включает игровые формы, что делает изчение языка увлекательным. Закончила курс А1, теперь учусь здесь же на следующей ступени. Все супер! Спасибо за позитив!",
                            Signature = "Ермилова Ольга"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2016, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Отличные курсы, я не пожалела ни капли,что пошла на них. Преподаватель Анхель лучший, объясняет доступно,понятно.Очень позитивный и добрейший человек. Занятия проходят в дружеской атмосфере. Я довольна, надеюсь продолжить занятия именно на этих курсах.",
                            Signature = "Александра Кирьянова",
                            SourceId = 1
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2016, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Очень-очень хорошие курсы. Приятная доброжелательная атмосфера. Удобное расписание. Каждый может выбрать оптимальное время для себя. Достаточно неформальное общение между студентами и преподавателями. Сама занимаюсь второй год и очень довольна.",
                            Signature = "Елена Титова",
                            SourceId = 4
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2013, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Хожу в школу на испанский язык уже второй год. Всем советуют. Обучение проводят педагоги носителя языка, что не мало важно, так как сразу грамотно ставят речь. Также очень удобное место расположение.",
                            Signature = "Надежда Горбачук",
                            SourceId = 4
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2014, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Perdonad, voy a escribir en ruso. Прекрасный, очень уютный, очень доброжелательный цент, при этом, работающий четко и профессионально. Редкое сочетание для Москвы. Отдельно отмечу прекрасного преподавателя, у которого училась Roger Vila. Надеюсь когда-нибудь продолжить.",
                            Signature = "Maria Tortuga",
                            SourceId = 4
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2015, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "По качеству преподавания центр Vamos для меня лучший из трех, где я проходил обучение.",
                            Signature = "Ильдар Хузин",
                            SourceId = 4
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2014, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Отличная школа. Цены, преподаватели, администраторы, качество обучения и место расположения школы - все на высшем уровне. Очень дружественная атмосфера! Преподаватели не зациклены на какой-то программе и предлагают множество различных способов изучения и всегда подстраиваются под темп группы. Мы ходили на занятия как на праздник. За 3 месяца изучения языка в Vamos, приехав в Испанию я начала говорить. Можно выучить испанский язык действительно недорого. Всем рекомендую эту школу!!",
                            Signature = "Alena Sakharova",
                            SourceId = 4
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2014, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Изучаю испанский в центре Vamos в Москве уже 9 месяцев, планирую продолжить обучение в следующем году. Очень довольна качеством преподавания (не смотря на то, что у каждого преподавателя свой особенный стиль). Хочу отметить приятную атмосферу в центре, гибкий график занятий и индивидуальный подход к студентам. Расположение центра также довольно удобно, в случае переезда, выбирают офис в центре и близко к станциям метро. Классы проходят динамично, позитивно, с юмором. Настоящее живое общение с носителями языка. Так держать!;))",
                            Signature = "Катерина Самодумова",
                            SourceId = 4
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2015, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Хорошая школа, обучения проходят в дружественной и доверительной обстановке в игровой форме. К сожалению нет возможности продолжать пока заниматься, спасибо всем учителям, особенно нашему Julio Ruizy:-)",
                            Signature = "Наталья Монахова",
                            SourceId = 4
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2015, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Хороший центр для изучения испанского языка. Всегда дружелюбная обстановка, интересные люди. Важно, что все преподаватели nativos. Это мне нравится больше всего. Удобное расположение Центра - в центре Москвы. Погружаешься в испанский мир и на время занятий забываешь обо всех заботах дня. Спасибо за обучение! Я очень рада, что училась в вашей школе. Вы стали моей дверью в Испанию.",
                            Signature = "Ирина Томчук",
                            SourceId = 4
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2015, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Центр очень хороший. Дружественное отношение преподавателей и администрации.",
                            Signature = "Наталья Захарова",
                            SourceId = 4
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2015, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Все хорошо, но хотелось бы побольше объяснения на русском языке.",
                            Signature = "Наталия",
                            SourceId = 4
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTime(2015, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "В целом мне все понравилось, но хотелось бы больше объяснения грамматики.",
                            Signature = "Нина",
                            SourceId = 4
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTime(2015, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Все хорошо! Мне нравится ваша школа, и я хочу продолжать обучение.",
                            Signature = "Екатерина",
                            SourceId = 4
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateTime(2015, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Это пока лучший центр, где я обучался.",
                            Signature = "Игорь"
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateTime(2015, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Учусь в школе в настоящее время!Восторг!!!! Каждый раз, как на праздник ✌️",
                            Signature = "Alexandra Sorokina",
                            SourceId = 1
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateTime(2015, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Учусь в этой школе почти 2 года. Дружеская, семейная атмосфера, небольшие группы. Преподают носители языка. На занятиях очень интересно и весело. Эффект есть, в Испании свободно разговариваю, почти нет языкового барьера. Учусь у Орьола. Всем рекомендую!",
                            Signature = "Luba Zimina"
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateTime(2015, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "В Целом, занятия оправдали мои ожидания. Мой преподаватель умел донести материал, всегда был готов к уроку и оставил только положительные впечатлеия. Очень рада, что в моей группе преподавал именно он!",
                            Signature = "Анастасия",
                            SourceId = 4
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateTime(2016, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Я изучаю испанский язык в школе уже 4-й год и на каникулах решил подтянуть свои знания. Мне очень понравилось, что учительница спокойная, никогда не ругала за ошибки, а просто и понятно объясняла недочёты. Осталось приятное ощущение от общения. При случае обращусь опять за помощью.",
                            Signature = "Виталий Лукашев"
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateTime(2016, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = @"Дорогой Vamos! С удовольствием занимаемся у вас всей семьей, и прогресс налицо - всего через два месяца после того, как мы начали 'с нуля', уже общались в Испании с живыми испанцами на разные темы, включая разговор в автосалоне по поводу тест-драйва и беседу в банке, а рестораны вообще не представляют никакой проблемы 
Нам очень нравятся наш el profesor - Йосу.Уроки интересные,
живые,
и,
как мы уже сказали,
полезные и ориентированные на 'быстрый запуск' разговорных навыков.С точки зрения грамматики мы уже знаем целых 5 времен,
что позволяет понимать общий смысл оригинальных текстов.
Мы рады,
что нашли ваш центр,
и верим,
что с вашей помощью сможем достичь того уровня владения языком,
с которого можно будет продолжать совершенствоваться и самостоятельно.Спасибо!",
                            Signature = "Андрей, Света, Аня, Соня"
                        },
                        new
                        {
                            Id = 21,
                            Date = new DateTime(2016, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Я обучалась в течении 3-х лет (правда, с перерывами в обучении), у разных преподавателей. Мне очень трудно было первые два-три урока, но потом, н мере увелечения словарного запаса - легче. Очень нравится, что преподаватели - носители языка - это заставляет напрягаться, думать, искать синонимы, не не говорить по-русски. Атмосфера в классе дружелюбная, почти семейная, заниматься интересно.",
                            Signature = "Родина Анна"
                        },
                        new
                        {
                            Id = 22,
                            Date = new DateTime(2016, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Я начала изучать испанский язык с нуля. Никогда не думала,что изучать язык может быть так познавательно, весело и захватывающе, т.к. из школьного детства всплывали совершенно другие воспоминания. Всем рекомендую эту школу испанского языка! Приходите заниматься, не бойтесь открывать новые страницы своей жизни!",
                            Signature = "Анжелика Ластенкова"
                        },
                        new
                        {
                            Id = 23,
                            Date = new DateTime(2016, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Учусь в школе с октября 2015г. практически с нуля. До этого три месяца занималась с репетитором, не понравилось категорически. В школе все совершенно иначе: у нас потрясающий преподаватели, обладающие фантастическим терпением, очень внятно все объясняющие и безгранично добрые. При этом постоянно хвалят и поддерживают. Готовы повторять и исправлять миллион раз, с отличным здоровым чувством юмора, весьма изобретательны и артистичны: споют, станцуют, принесут какое-нибудь занимательное кино. У них широкий кругозор, на каждом уроке обязательно расскажут какие-то интересные факты и истории. Т.е. мы не только учим испанский, но еще узнаем много нового и интересного. У нас потрясающая группа: на уроках царит дружелюбная атмосфера, мы очень много смеемся, фонтанируем какими-то идеями. В общем, занятия испанским языком в школе VAMOS это и знания, и досуг, и знакомство с новыми людьми, и расширение кругозора. Большое спасибо также администраторам школы! С ними всегда можно связаться по любому вопросу и на все получить ответ и помощь. Все сотрудники школы очень добрые и позитивные люди. И даже если вы придете на занятие уставшим, взвинченным и нервным, то выйдете с урока с улыбкой!",
                            Signature = "Ольга Трубилова"
                        },
                        new
                        {
                            Id = 24,
                            Date = new DateTime(2016, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Я выбирала курсы испанского через Интернет и нисколько не разочаровалась! Мне нравится и все подходит: и месторасположение, и время занятий, и класс, и компания, и продолжительность урока, и наполнение, и темп, и конечно наш преподаватель. У него несомненно талант преподавания. Каждое занятие с ним - это восторг! Очень тяжело после рабочего дня приходить в класс и усваивать что-то новое, приходится заставлять себя. Но стоит прийти и включиться - вся усталость пропадает! Наш преподаватель бесконечно терпелив и неизменно доброжелателен с каждым. Считаю, мне очень повезло! Кроме того, у нас подобралась отличная группа, мне нравятся все ребята, хочется учиться с ними дальше. Спасибо Наталье за оперативное решение всех вопросов и отличную организацию занятий!",
                            Signature = "Татьяна"
                        },
                        new
                        {
                            Id = 25,
                            Date = new DateTime(2016, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Я ещё не закончила заниматься на курсах, но уже поняла, что мой выбор был абсолютно правильным! Сначала я хотела позаниматься только на начальном уровне, но мне так понравилось, что я решила продолжить. Я более 30 лет преподаю английский язык и разбираюсь в методиках. На наших курсах методика самая лучшая! Мой преподаватель Йосу очень хороший и ответственный учитель, мне нравится, как он нас обучает. Йосу любит свою работу, и это всегда видно ученикам и мотивирует их на учёбу. Я желаю и Йосу, и всем остальным преподавателям наших курсов успехов в работе, и пусть к вам не зарастает народная тропа!",
                            Signature = "Маргарита Чурина"
                        },
                        new
                        {
                            Id = 26,
                            Date = new DateTime(2017, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Я была в Испании с октября по январь, и вот теперь опять я здесь с конца апреля. Курсы мне конечно очень и очень помогли, Рафа дал отличную основу, он отличный Учитель! Когда я была здесь осенью, я ходила на местные курсы для иностранцев, там Учитель постоянно говорит быстро на испанском, понимай, как хочешь, но через какое-то время начинаешь общаться как-то от неизбежности. И опять же, конечно, без Вашей школы и Рафы я бы там вообще ничего не поняла, ходила постоянно с нашими распечатками и тетрадями Я, кстати, рекомендовала нашу школу одной мое знакомой, она тоже хотела учить испанский Спасибо, что вы такие внимательные! Всегда на связи с учениками! Это здорово! Рафе от меня большой привет!",
                            Signature = "Фаримжанова Динара"
                        },
                        new
                        {
                            Id = 27,
                            Date = new DateTime(2016, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Этим летом я поехала учить испанский в Валенсию. Очень приятная школа испанского языка…. Хорошее сочетание высокого уровня образования и красивого и жаркого города с отличными пляжами. Я училась там в течении 3-х недель и заметно подтянула свой уровень испанского! Валенсия- очень приятный город, школа располагается в самом центре, в симпатичном квартале, в пешей доступности от всех достопримечательностей, город- не дорогой и люди очень открытые и дружелюбные. И можно бегать в парке с другими помешенными на спорте людьми, как никогда… Спасибо International House Valencia за чудесный опыт! Спасибо моей школе испанского языка в Москве (Vamos), которая мне посоветовала поехать в Валенсию! Незабываемые впечатления!",
                            Signature = "Екатерина Шишканова"
                        },
                        new
                        {
                            Id = 28,
                            Date = new DateTime(2018, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Добрый день! Пишу Вам из Сантьяго:) Оказалось, у меня хороший испанский, я могу сама покупать поездки, еду и перемещаться, меня прекрасно понимают:) А в школе испанского были удивлены, что этот уровень я освоила за ваших 2,5 курса. Ещё раз спасибо большое за базу, только здесь поняла, что разговариваю на испанском."
                        },
                        new
                        {
                            Id = 29,
                            Date = new DateTime(2018, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Я занималась в школе Vamos около года. Обучение было очень продуктивным и интересным - все уроки буквально на одном дыхании. Огромное спасибо Рафаэлю, Анхелю и Альберто за это! Сейчас я продолжаю обучение в Испании и очень уверенно чувствую себя на занятиях. Местные жители думают, что я училась минимум лет 5 и очень удивляются, когда я говорю, что всего год в России. Если сравнивать обучение в школе Vamos и в испанской школе, то могу сказать, что по многим параметрам (цена, индивидуальный подход, использование игровых практик и тд) учеба в школе Vamos лучше. Рекомендую всем! Удачи в изучении испанского!",
                            Signature = "Екатерина Шишканова"
                        },
                        new
                        {
                            Id = 30,
                            Date = new DateTime(2019, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Message = "Огромное спасибо школе Vamos и отличному преподавателю Хулио за прекрасную подачу материала и за настроение, которое он создавал на занятиях!! Мы много общались и смеялись) и группа подобралась веселая, что тоже немаловажно)) уроки очень интенсивные, но при этом информация усваивается хорошо и даже почти легко. Огромный плюс в том, что преподаватель почти не говорит по-русски, и с первых уроков ты начинаешь воспринимать настоящую испанскую речь, что помогает потом, по крайней мере в путешествиях.",
                            Signature = "Татьяна"
                        });
                });

            modelBuilder.Entity("CESP.Database.Context.Users.Models.FeedbackSourceDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("feedback_sources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "facebook"
                        },
                        new
                        {
                            Id = 2,
                            Name = "vk"
                        },
                        new
                        {
                            Id = 3,
                            Name = "e-mail"
                        },
                        new
                        {
                            Id = 4,
                            Name = "анкета"
                        });
                });

            modelBuilder.Entity("CESP.Database.Context.Users.Models.UserDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasMaxLength(256);

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasMaxLength(256);

                    b.Property<string>("Phone")
                        .HasColumnName("phone")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("CESP.Database.Context.Education.Models.SpeakingClubMeetingDto", b =>
                {
                    b.HasOne("CESP.Database.Context.Education.Models.LanguageLevelDto", "MaxLanguageLevel")
                        .WithMany()
                        .HasForeignKey("max_language_meeting_fk")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CESP.Database.Context.Education.Models.LanguageLevelDto", "MinLanguageLevel")
                        .WithMany()
                        .HasForeignKey("min_language_meeting_fk")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CESP.Database.Context.Education.Models.TeacherDto", "Teacher")
                        .WithMany()
                        .HasForeignKey("teacher_meeting_fk")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CESP.Database.Context.Education.Models.StudentGroupDto", b =>
                {
                    b.HasOne("CESP.Database.Context.Education.Models.CourseDto", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .HasConstraintName("student_group_course_fk")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CESP.Database.Context.Education.Models.StudentGroupPriceDto", b =>
                {
                    b.HasOne("CESP.Database.Context.Payments.Models.PriceDto", "Price")
                        .WithMany()
                        .HasForeignKey("PriceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CESP.Database.Context.Education.Models.StudentGroupDto", "StudentGroup")
                        .WithMany()
                        .HasForeignKey("StudentGroupId")
                        .HasConstraintName("student_group_price_student_group_fk")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CESP.Database.Context.Payments.Models.PriceDto", b =>
                {
                    b.HasOne("CESP.Database.Context.Payments.Models.CurrencyDto", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .HasConstraintName("price_currency_fk")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CESP.Database.Context.Payments.Models.PaymentPeriodDto", "PaymentPeriod")
                        .WithMany()
                        .HasForeignKey("PaymentPeriodId")
                        .HasConstraintName("price_payment_period_fk")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CESP.Database.Context.Schedules.Models.ScheduleDto", b =>
                {
                    b.HasOne("CESP.Database.Context.Schedules.Models.ScheduleDayDto", "ScheduleDay")
                        .WithMany()
                        .HasForeignKey("ScheduleDayId")
                        .HasConstraintName("schedule_schedule_day_fk")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CESP.Database.Context.Education.Models.StudentGroupDto", "StudentGroup")
                        .WithMany()
                        .HasForeignKey("StudentGroupId")
                        .HasConstraintName("schedule_student_group_fk")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CESP.Database.Context.Users.Models.FeedbackDto", b =>
                {
                    b.HasOne("CESP.Database.Context.Users.Models.FeedbackSourceDto", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .HasConstraintName("feedback_source_fk")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CESP.Database.Context.Users.Models.UserDto", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("feedback_user_fk")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
